version: 2

jobs:

  lint:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: node_modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn lint

  test:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: node_modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn test:coverage

  build:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: node_modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn build

workflows:
  version: 2
  validate:
    jobs:
      - lint
      - test
