# Site settings
title: immutad●t
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  is a set of immutable functions using dot notation.
baseurl: "" # the subpath of your site, e.g. /newpath-for-emping
url: "immutadot.zenika.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
GoogleAnalytics: UA-xxxxxx-x

twitter:
  username: rmsubekti
facebook:
  app_id: 1234567
  publisher: 1234567

sass:
    style: compressed

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
  smart_quotes: ["apos", "apos", "quot", "quot"]

gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

defaults:
    - {scope: {type: posts}, values: {layout: post, permalink: '/blog/:title'}}

include:
  - _pages

exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock

paginate: 12
paginate_path: '/blog/:num'
